Add check_domain action

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -11,6 +11,14 @@ jobs:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
+          
+      - name: Validate CNAME
+        run: |
+          if [ ! -f public/CNAME ]; then
+            echo "❌ CNAME file missing!" >&2
+            exit 1
+          fi
+          echo "✅ CNAME verification passed"
 
       - name: Setup Hugo
         uses: peaceiris/actions-hugo@v2
